### ISSUE TITLE
cant connect https with xpack.security.enabled

### ISSUE THREAD

**Issue by xiaoyeshiyu** [StephaneBour/sense-chrome#26]
```
xpack.security.enabled: true

xpack.security.http.ssl:
  enabled: true
  keystore.path: certs/http.p12
```

I can open :9200 web with username and password, but cant with sense-chrome.
Need this feature PLZ....
